name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: "Install dependencies"
        run: npm install

      - name: "Build App"
        run: npm run build

      - name: "Setup chromedriver"
        uses: nanasess/setup-chromedriver@master
        with: 
          chromedriver-version: '88.0.4324.96'
      - run: chromedriver --url-base=/wd/hub &

      - name: 'Run test'
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
            heroku_email: ${{secrets.HEROKU_EMAIL}}

